// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2RRrnZlQ8Q8RRyzAuaxSGVptx6sCLQ0I',
    appId: '1:452221103090:web:a69f8badb809b786ef996b',
    messagingSenderId: '452221103090',
    projectId: 'levant-sale-application',
    authDomain: 'levant-sale-application.firebaseapp.com',
    storageBucket: 'levant-sale-application.firebasestorage.app',
    measurementId: 'G-MDQN0RN2LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQKomriiw-7wy-Y3T_3mrIWuFKYdcpIRs',
    appId: '1:452221103090:android:9e44e83571f21b72ef996b',
    messagingSenderId: '452221103090',
    projectId: 'levant-sale-application',
    storageBucket: 'levant-sale-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Ms7gR9B4Xzq7u4YPr6ewFy7L7gA6i14',
    appId: '1:452221103090:ios:4f39a273063ea615ef996b',
    messagingSenderId: '452221103090',
    projectId: 'levant-sale-application',
    storageBucket: 'levant-sale-application.firebasestorage.app',
    androidClientId: '452221103090-a4205rtopekbudhqg1n3gf7ebsh75dc5.apps.googleusercontent.com',
    iosClientId: '452221103090-99p45q6q4o0l1eamut8e8cbje9tqbb01.apps.googleusercontent.com',
    iosBundleId: 'com.levantsale.levantsale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5Ms7gR9B4Xzq7u4YPr6ewFy7L7gA6i14',
    appId: '1:452221103090:ios:46077a6615ec724aef996b',
    messagingSenderId: '452221103090',
    projectId: 'levant-sale-application',
    storageBucket: 'levant-sale-application.firebasestorage.app',
    iosClientId: '452221103090-m0n1jekf2i6rtrbdndnrttrlvfvcu6o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.tajawal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2RRrnZlQ8Q8RRyzAuaxSGVptx6sCLQ0I',
    appId: '1:452221103090:web:06f47785f0fd5897ef996b',
    messagingSenderId: '452221103090',
    projectId: 'levant-sale-application',
    authDomain: 'levant-sale-application.firebaseapp.com',
    storageBucket: 'levant-sale-application.firebasestorage.app',
    measurementId: 'G-ZNJDVXKCVT',
  );
}